In [1]:
s3_credentials = open('creds.json').read()
import json
s3_creds = json.loads(s3_credentials)

In [2]:
import pandas as pd

In [3]:
df_viewing = pd.read_csv('core_viewing.csv')
df_viewing.head()

,viewer_id,viewer_id_type,visit_id,platform_id,date_id,date_and_time_local,isp,production_id,stream_id,stream_requests,stream_playing_time
0,e17b67bd-4256-475d-bea2,R,09752b70-c53e-4ba9-a22a-10d92c486b9d-154714670...,550,20190110,2019-01-10 18:58:30.055000,BT,2/5386/0003#001,eff53a93-3ef8-4fcb-a0f1-8094dce839a6,1,52.676
1,51be9e2e-0443-462c-a7dc,R,271104c3-8c03-4fc3-928b-beb080d3b64c-154668453...,551,20190105,2019-01-05 11:24:00.455000,Post Office Broadband,2/5336/0003#001,dc483ce6-498b-4d9b-9178-acda35d95947,0,0.000
2,562129d1-ed99-4d4e-9e59,R,f6aaed61-7fda-44b1-8e16-a9c57490c69d-154645145...,547,20190102,2019-01-02 18:01:16.326000,BT,1/5163/2841#001,c01e58e4-6061-4ba6-8800-3cbb56a4c874,0,0.000
3,6a7b6c19-71c6-42f9-92fa,R,e69ef4b2-d675-4b10-b9ae-ddc971d496a9-154741975...,120,20190113,2019-01-13 22:49:40.359000,JTGlobal,2/3296/0038#001,f4b3581e-e382-4cb0-bd5e-e80eb59a786a,0,0.000
4,f710927a-e7bb-4a9b-aecb,R,f3dec6b9-5849-4b06-bb0e-3bc0ffcaab70-154789172...,120,20190119,2019-01-19 10:01:13.785000,TalkTalk,1/7442/0046#001,3102d8a5-6922-41f9-9579-ccb05f1b0c0e,0,0.000

In [4]:
df_viewing.set_index('viewer_id', inplace = True)
df_viewing.head()

,viewer_id_type,visit_id,platform_id,date_id,date_and_time_local,isp,production_id,stream_id,stream_requests,stream_playing_time
viewer_id,,,,,,,,,,
e17b67bd-4256-475d-bea2,R,09752b70-c53e-4ba9-a22a-10d92c486b9d-154714670...,550,20190110,2019-01-10 18:58:30.055000,BT,2/5386/0003#001,eff53a93-3ef8-4fcb-a0f1-8094dce839a6,1,52.676
51be9e2e-0443-462c-a7dc,R,271104c3-8c03-4fc3-928b-beb080d3b64c-154668453...,551,20190105,2019-01-05 11:24:00.455000,Post Office Broadband,2/5336/0003#001,dc483ce6-498b-4d9b-9178-acda35d95947,0,0.000
562129d1-ed99-4d4e-9e59,R,f6aaed61-7fda-44b1-8e16-a9c57490c69d-154645145...,547,20190102,2019-01-02 18:01:16.326000,BT,1/5163/2841#001,c01e58e4-6061-4ba6-8800-3cbb56a4c874,0,0.000
6a7b6c19-71c6-42f9-92fa,R,e69ef4b2-d675-4b10-b9ae-ddc971d496a9-154741975...,120,20190113,2019-01-13 22:49:40.359000,JTGlobal,2/3296/0038#001,f4b3581e-e382-4cb0-bd5e-e80eb59a786a,0,0.000
f710927a-e7bb-4a9b-aecb,R,f3dec6b9-5849-4b06-bb0e-3bc0ffcaab70-154789172...,120,20190119,2019-01-19 10:01:13.785000,TalkTalk,1/7442/0046#001,3102d8a5-6922-41f9-9579-ccb05f1b0c0e,0,0.000

In [5]:
df_viewing.dtypes

viewer_id_type          object
visit_id                object
platform_id              int64
date_id                  int64
date_and_time_local     object
isp                     object
production_id           object
stream_id               object
stream_requests          int64
stream_playing_time    float64
dtype: object

In [6]:
import boto3
from io import StringIO

def df_to_s3(df, bucket, key, s3_access_key, s3_secret_key):

    session = boto3.Session(aws_access_key_id = s3_access_key,
                            aws_secret_access_key = s3_secret_key)
    s3 = session.resource('s3')
    csv_buffer = StringIO()
    df.to_csv(csv_buffer)

    s3.Object(bucket, key).put(ServerSideEncryption = 'AES256', Body = csv_buffer.getvalue()[1:])
    return print('Successfully uploaded data to s3 bucket!')

if __name__ == '__main__':

    file = ''
    bucket_name = 'svv-s3-dev-scratch'
    s3_access_key = s3_creds['access_key']
    s3_secret_key = s3_creds['secret_key']
    
    hub_sql_test_key = 'core_viewing.csv'

    df_to_s3(df_viewing, bucket_name, hub_sql_test_key, s3_access_key, s3_secret_key)

Successfully uploaded data to s3 bucket!